server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Habilitar compresión Gzip para mayor velocidad
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Esto es crucial para Vue Router (history mode)
        # Si no se encuentra un archivo real, redirige todo a index.html
        try_files $uri $uri/ /index.html;
    }

    # Caché estático para imágenes, CSS y JS
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
